DROP TABLE IF EXISTS PUSH_MESSAGE;

CREATE TABLE IF NOT EXISTS PUSH_MESSAGE (
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CONTENT VARCHAR(255),
    STATUS VARCHAR(10),
    CREATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP
);